# This pipeline is only meant to be used by docker base images
# should only build and push from the main branch
# and do a nightly build between 00 - 06

# There will always be 2 tags to every build
  # the first tag contains date of the build, buildversion and 4 first chars from the builds commit sha
  # the second tag: "latest" will always be replace the previous existing latest
  # this will provide a linear insight in the build history and the default tag "latest" always can be used to get the latest version

pr: none
trigger:
  branches:
    include:
      - main

schedules:
  - cron: "00 02 * * *" 
    displayName: nightly build
    branches:
      include:
        - main

variables:
  - group: cet-general-params
  - group: cet-ref
  - name: dockerfilePath
    value: "$(Pipeline.Workspace)/github/Dockerfile"
  - name: imageName
    value: kth-nodejs-18
  - name: tag
    value: "${BUILD_BUILDNUMBER}_${BUILD_SOURCEVERSION:0:4}"

resources:
  repositories:
    - repository: cet-iac
      type: git
      name: Cloud Excellence Team/cet-iac
      ref: main

pool:
  vmImage: "ubuntu-latest"

steps:
  - template: templates/docker/base-image-build-push.yml@cet-iac
    parameters:
      runScan: true
      dockerFilePath: $(dockerfilePath)
      imageName: $(imageName)
      tag: $(tag)