# This pipeline is only meant to be used by docker base images
# should only build and push from the main branch
# and do a nightly build between 00 - 06

# There will always be 2 tags to every build
  # the first tag contains date of the build, buildversion and 4 first chars from the builds commit sha
  # the second tag: "latest" will always be replace the previous existing latest
  # this will provide a linear insight in the build history and the default tag "latest" always can be used to get the latest version

pr: none
trigger:
  branches:
    include:
      - main

schedules:
  - cron: "30 1 * * 1-5"
    displayName: nightly build
    branches:
      include:
        - main
    always: true

variables:
  - group: cet-general-params
  - name: dockerfilePath
    value: "$(Pipeline.Workspace)/github/Dockerfile"
  - name: imageName
    value: kth-nodejs-18
  - name: tag
    value: "${BUILD_BUILDNUMBER}_${BUILD_SOURCEVERSION:0:4}"
  - name: workspace
    value: '$(Pipeline.Workspace)/github'

resources:
  repositories:
    - repository: stratus-templates
      type: git
      name: Cloud Excellence Team/stratus-templates
      ref: main

pool:
  vmImage: "ubuntu-latest"

extends:
  template: templates/security/security-scans.yml@stratus-templates
  parameters:
    steps:
    - template: /templates/test/docker.yml@stratus-templates
      parameters: 
        dockerComposeFilePaths:
          - '$(Pipeline.Workspace)/github/docker-compose-unit-tests.yml'
          - '$(Pipeline.Workspace)/github/docker-compose-integration-tests.yml'
        dockerFilePath: $(dockerFilePath)
        projectName: $(imageName)
        imageName: $(imageName)
        tag: $(tag)

    - template: /templates/docker/push.yml@stratus-templates
      parameters:
        build: true
        dockerFilePath: $(dockerfilePath)
        imageName: $(imageName)
        tag: $(tag)
